-- 코드를 입력하세요
SELECT CATEGORY, sum(sales) as TOTAL_SALES
from BOOK JOIN BOOK_SALES
using(BOOK_ID)
where SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
group by category
order by category asc;

# SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
# FROM BOOK_SALES S JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# WHERE SALES_DATE LIKE '2022-01%'
# GROUP BY CATEGORY
# ORDER BY 1 ASC
